### PR TITLE
Add options for Filename templates to resolve relative paths using source file location

### PR DESCRIPTION
**Pull request by arroyoj**
These two commits allow confuse ConfigSources and Filename templates to be set up to resolve relative paths from the base directory of the configuration file itself, rather than the application's configuration directory. The new behavior is opt-in.

The first commit implements the new relative path behavior at the ConfigSource level, by allowing the source file to be marked as resolving paths relative to its base directory. This was the suggested approach in response to #125.

The second commit provides an additional way to invoke the new relative path behavior at the level of an individual template, regardless of the setting for the source. This could potentially allow applications to have more fine-grained control over path resolution. It would also allow applications to resolve paths in the application's default `config_default.yaml` file relative to that location within the package. This could be useful for packages with default settings that refer to a default data file. However, if it is not desirable to have two ways to invoke the same behavior, the second commit could be dropped.

### CODE REVIEW

**Comment by arroyoj** [comment]
@sampsyo, thank you for merging in my other template updates. It has been great to see them become part of the library. If you have time, I was hoping to get your comments on this earlier PR to provide an alternative behavior for resolving relative paths with `Filename` templates. Given all of the other commits and merges since I made this PR, I also wasn't sure if you'd prefer that I rebase onto the current master, or leave it as is.

**Comment by sampsyo** [comment]
Thanks for the ping! This looks great overall. My only thought is about documentation. The docstring covers the per-template version of the behavior pretty well, but maybe we should describe what's going on with `base_for_paths` as well?

And would a new description of the two different options for this behavior make sense in the "prose" documentation, aside from the docstrings?

**Comment by arroyoj** [comment]
Thanks for the feedback. Yes, expanding the documentation sounds good. I'll work on that and then update the PR.

**Comment by arroyoj** [comment]
@sampsyo, in addition to providing documentation, I made a few small changes to the previous code. I realized that in my original implementation, the `base_for_paths` parameter of the source would override the `in_app_dir` parameter of the `Filename` template, but I felt that any parameters passed to the template should take precedence over the source-level setting. The new version makes that the case and adds some tests for it. I also provided another entry point for using the `base_for_paths` parameter by adding it to the `set_file` method. This way, one can use that feature using just the `Configuration` object interface without needing to create a `ConfigSource` or `YamlSource` directly.

**Review by sampsyo — APPROVED** [review]
This all looks amazing!!! So many apologies for how long it took me to review, but I think this seems perfect—I'll merge it now. :sparkles:

**Comment by arroyoj** [comment]
Thanks for merging in this PR. It has been a great experience contributing to this project. Now that there are several updates to the templates from this and the other recent PRs, would you consider doing a version bump and new release? Happy to help if I can.

**Comment by sampsyo** [comment]
Yes; good call! I'll do this shortly.

**Comment by sampsyo** [comment]
OK, published v1.5.0! https://pypi.org/project/confuse/

**Comment by arroyoj** [comment]
That's great. Thanks!

**Pull request merged**
