### PR TITLE
Make pathlib object convertible to a 'Template'

### PR DESCRIPTION
**Pull request by ntqr**
```python
>>> from pathlib import Path
>>> import confuse
>>> config = confuse.Configuration('default-path')
>>> config['default-path'].get(Path.home())
WindowsPath('C:/Users/Me')
>>> config['default-path'] = 'D:\\'
>>> config['default-path'].get(Path.home())
WindowsPath('D:/')
```

### CODE REVIEW

**Comment by sampsyo** [comment]
Looks excellent; thanks! Would you mind handling an `ImportError` for `pathlib` so this works even on Python versions that don't have it (<3.4)?

**Comment by ntqr** [comment]
Should I add a check for the one in templates.Path too? Or should I just move both of the imports to the top?

**Comment by sampsyo** [comment]
Good question, but that one doesn't need a check (although it should not be moved to the top) because it is only useful if pathlib is available. In contrast, `as_template` should work if pathlib is not available.

**Comment by ntqr** [comment]
Not sure if this is the good way to do it, what do you think?

**Comment by sampsyo** [comment]
That absolutely works; thanks!!

**Pull request merged**
