### PR TITLE
add reload function

### LINKED ISSUE #138: Hot reloading
Hi,

I was wondering if this cool library can perform hot reloading to update config in live if the file changed. 

Eg:

`main.py`
```python
import confuse
import sys
import time

if __name__ == "__main__":
  config = confuse.Configuration('app', __name__)
  print(config)
  time.sleep(20)
  print(config)
  sys.exit(0)
```

`~/.config/app/config.yaml`
```yaml
foo: bar
```

I launch the program, then I modify the `config.yaml` file to 
```yaml
foo: bar
test: hello world
```

Program output:
```bash
$ python3 main.py
{'foo': 'bar'}  # I change the config.yaml file after this output
{'foo': 'bar'}  # Sould be {'foo': 'bar', 'test': 'hello world'}
# Relaunching program to be sure 
% python3 main.py
{'foo': 'bar', 'test': 'hello world'}
{'foo': 'bar', 'test': 'hello world'}
```

Thanks

### PR DESCRIPTION
**Pull request by pbrissaud**
Adding a function to reload the function. 

Closes #138

### CODE REVIEW

**Comment by pbrissaud** [comment]
Hi, I try to add a test function but I get this error  

```python
 def test_reload_conf(self):
   with TempDir() as temp:
     path = temp.sub('test_config.yaml', b'foo:bar')
     config = confuse.Configuration('test', __name__)
     config.set_file(filename=path)
     self.assertEqual(config['foo'], 'bar')
     temp.sub('test_config.yaml', b'foo:bar2\ntest: hello world')
     config.reload()
     self.assertEqual(config['foo'], 'bar2')
     self.assertEqual(config['test'], 'hello world')
```

```
Error
Traceback (most recent call last):
  File "/Users/pbrissaud/IdeaProjects/confuse/test/test_yaml.py", line 46, in test_reload_conf
    config.set_file(filename=path)
  File "/Users/pbrissaud/IdeaProjects/confuse/confuse/core.py", line 667, in set_file
    self.set(YamlSource(filename, base_for_paths=base_for_paths,
  File "/Users/pbrissaud/IdeaProjects/confuse/confuse/sources.py", line 76, in __init__
    self.load()
  File "/Users/pbrissaud/IdeaProjects/confuse/confuse/sources.py", line 86, in load
    self.update(value)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

Do you have a idea how to fix this ?

**Comment by sampsyo** [comment]
Cool! I think it may be the YAML syntax: `foo:bar` isn't a valid mapping because it's missing whitespace. Changing that to `foo: bar` might help.

**Comment by pbrissaud** [comment]
That was so obvious ! Thanks

**Comment by pbrissaud** [comment]
Testing function ✅

**Comment by sampsyo** [comment]
Awesome; thanks! I expanded the docstring a little bit and merged.

**Comment by pbrissaud** [comment]
Perfect, thanks ! Do you know when the new version including this PR will be published ?

**Comment by sampsyo** [comment]
Released!
https://pypi.org/project/confuse/1.6.0/

**Comment by pbrissaud** [comment]
Perfect 👌

**Pull request merged**
